name: Pull Request

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: soat-tech-challenge/github-workflows/.github/workflows/maven-and-docker-build.yml@main
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
